/******************************************************************************
 *
 * Module: Ultrasonic
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the Ultrasonic driver
 *
 * Author: Bilal Mohamed
 *
 *******************************************************************************/

#include "../MCAL/icu.h"
#include "../MCAL/gpio.h"
#include "ultrasonic.h"
#include <util/delay.h>

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/
uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;               //T1



/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*
 * Description :
 * Initialize the Ultrasonic driver:
 * Initialize the ICU driver
 * Setup the ICU call back function
 * Setup the direction for the trigger pin as output pin through the GPIO driver
 */
void Ultrasonic_init(void)
{
	/* Create configuration structure for ICU driver */
	Icu_ConfigType icu_config = {F_CPU_8,RISING};
	//initialize the ICU driver
	Icu_init(&icu_config);

	//Setup the ICU call back function
	Icu_setCallBack(Ultrasonic_edgeProcessing);

	//Setup the direction for the trigger pin as output pin through the GPIO driver
	GPIO_setupPinDirection(PORTB_ID, PIN5_ID, PIN_OUTPUT);
}


/* Description :
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void)
{
	/* Write one on the trigger pin to start the pulse */
	GPIO_writePin(PORTB_ID, PIN5_ID, LOGIC_HIGH);

	_delay_us(50); /* delay for processing = 50 us */

	/* Write zero on the trigger pin to end the pulse */
	GPIO_writePin(PORTB_ID, PIN5_ID, LOGIC_LOW);
}



/*
 * Description :
 * Send the trigger pulse by using Ultrasonic_Trigger function
 * Start the measurements by the ICU from this moment
 */
uint16 Ultrasonic_readDistance(void)
{
	Ultrasonic_Trigger();

	/* Waiting until the ultrasonic receive the transmitted ultrasound wave*/
	while(g_edgeCount != 2);

	g_edgeCount = 0;

	return g_timeHigh/58 + 1;
}

/*
 * Description :
 * This is the call back function called by the ICU driver
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;

	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		Icu_setEdgeDetectionType(FALLING);       /* Detect falling edge */
	}
	else if(g_edgeCount == 2)
	{
		g_timeHigh = Icu_getInputCaptureValue(); /* Store the High time value(T1) */

		/* Clear the timer counter register to start measurements again */
		Icu_clearTimerValue();

		Icu_setEdgeDetectionType(RISING);       /* Detect raising edge */
	}
}
